const fs = require('node:fs');
const assert = require('node:assert/strict');
const Controller = class {};
const source = fs.readFileSync('app/javascript/controllers/ai_modal_controller.js', 'utf8').replace(/^import .*\n/, '').replace('export default class', 'class AiModalController');
const Klass = eval(source + '\nAiModalController');
const setInterval = () => 1;
const clearInterval = () => {};
let calls = 0;
let resolveResponse;
const fetch = () => { calls++; return new Promise(resolve => { resolveResponse = resolve; }); };
const c = new Klass();
c.element = {classList: {add: () => {}, remove: () => {}}};
c._enableSubmit = () => {};
c._replacePendingItemHtml = () => {};
(async () => {
  c.pendingChatId = 1; c.pendingStatusUrl = '/chat/1'; c.pendingSince = Date.now();
  const first = c._pollPendingStatus();
  await c._pollPendingStatus();
  assert.equal(calls, 1);
  const request = c._pollRequest;
  c.close();
  assert(request.signal.aborted);
  resolveResponse({ok: true, json: async () => ({ready: true})});
  await first;
  assert.equal(c.pendingChatId, 1);
  c.pendingSince = Date.now() - 61000;
  await c._pollPendingStatus();
  assert.equal(c.pendingChatId, null);
  assert.equal(calls, 1);
  c.pendingChatId = 2; c.pendingStatusUrl = '/chat/2'; c.pendingSince = Date.now();
  const missing = c._pollPendingStatus();
  resolveResponse({ok: false, status: 404});
  await missing;
  assert.equal(c.pendingChatId, null);
  c.pendingChatId = 3; c.pendingStatusUrl = '/chat/3'; c.pendingSince = Date.now();
  const failed = c._pollPendingStatus();
  resolveResponse({ok: false, status: 500});
  await failed;
  c.pendingSince = Date.now() - 61000;
  await c._pollPendingStatus();
  assert.equal(c.pendingChatId, null);
  console.log('PASS: polling prevents overlapping requests, aborts on close, ignores stale responses, stops on missing chats and times out despite HTTP failures');
})();
