const fs = require('node:fs');
const assert = require('node:assert/strict');
const source = fs.readFileSync('app/javascript/controllers/search_controller.js', 'utf8').replace(/^import .*\n/, '').replace('export default class', 'class SearchController');
const Controller = class {};
let fireTimer;
const setTimeout = fn => { fireTimer = fn; return 1; };
const clearTimeout = () => {};
const requests = [];
const fetch = (url, options) => new Promise(resolve => requests.push({url, options, resolve}));
const current = {innerHTML: 'initial'};
const document = {getElementById: () => current};
const window = {location: {origin: 'https://example.test'}, history: {replaceState: () => {}}};
const DOMParser = class {parseFromString(text) { return {getElementById: () => ({innerHTML: text})}; }};
const Klass = eval(source + '\nSearchController');
const c = new Klass();
c.connect();
c.urlValue = '/en/blog';
c.delayValue = 300;
c.element = {querySelector: () => ({value: '42'})};
const flush = () => new Promise(r => global.setImmediate(r));
(async () => {
  c.changed({target: {value: 'old'}}); fireTimer();
  c.changed({target: {value: 'new'}});
  assert(requests[0].options.signal.aborted);
  requests[0].resolve({ok: true, text: async () => 'old results'});
  await flush();
  assert.equal(current.innerHTML, 'initial');
  fireTimer();
  assert.equal(requests[1].url, '/en/blog?tag_id=42&q=new');
  requests[1].resolve({ok: true, text: async () => 'new results'});
  await flush();
  assert.equal(current.innerHTML, 'new results');
  c.changed({target: {value: 'pending'}}); fireTimer();
  c.disconnect();
  requests[2].resolve({ok: true, text: async () => 'disconnected results'});
  await flush();
  assert.equal(current.innerHTML, 'new results');
  console.log('PASS: stale searches cannot render during debounce or after disconnect; tag filter is retained');
})();
