const fs = require('node:fs');
const assert = require('node:assert/strict');
const source = fs.readFileSync('app/javascript/controllers/tag_input_controller.js', 'utf8').replace(/^import .*\n/, '').replace('export default class', 'class TagInputController');
let fireTimer;
let requests = [];
const Controller = class {};
const setTimeout = (fn) => { fireTimer = fn; return 1; };
const clearTimeout = () => {};
const fetch = (url) => new Promise(resolve => requests.push({url, resolve}));
const Klass = eval(source + '\nTagInputController');
const c = new Klass();
c.selectedIds = new Set();
c.inputTarget = {value: 'old'};
c.consumeDelimitedInput = () => c.inputTarget.value;
c.renderStatus = () => {};
c.renderResults = items => c.visibleItems = items;
c.renderEmptyState = () => {};
c.listTarget = {innerHTML: ""};
c.clearList = () => { c.cancelSearch(); c.visibleItems = []; };
(async () => {
  c.search(); fireTimer();
  c.inputTarget.value = 'new'; c.search(); fireTimer();
  requests[1].resolve({ok: true, json: async () => [{id: 2, name: 'new'}]});
  await new Promise(r => global.setImmediate(r));
  assert.equal(c.visibleItems[0].name, 'new');
  requests[0].resolve({ok: true, json: async () => [{id: 1, name: 'old'}]});
  await new Promise(r => global.setImmediate(r));
  assert.equal(c.visibleItems[0].name, 'new');
  console.log('PASS: older tag response cannot overwrite newer suggestions');
  c.inputTarget.value = 'pending'; c.search(); fireTimer();
  c.inputTarget.value = ''; c.search();
  assert.deepEqual(c.visibleItems, []);
  requests[2].resolve({ok: true, json: async () => [{id: 3, name: 'pending'}]});
  await new Promise(r => global.setImmediate(r));
  assert.deepEqual(c.visibleItems, []);
  console.log('PASS: late tag response cannot reopen cleared suggestions');
  c.inputTarget.value = 'selected'; c.search(); fireTimer();
  c.clearList();
  requests[3].resolve({ok: true, json: async () => [{id: 4, name: 'selected'}]});
  await new Promise(r => global.setImmediate(r));
  assert.deepEqual(c.visibleItems, []);
  c.inputTarget.value = 'disconnected'; c.search(); fireTimer();
  global.document = {removeEventListener: () => {}};
  c.disconnect();
  requests[4].resolve({ok: true, json: async () => [{id: 5, name: 'disconnected'}]});
  await new Promise(r => global.setImmediate(r));
  assert.deepEqual(c.visibleItems, []);
  delete global.document;
  c.inputTarget.value = 'error'; c.search(); fireTimer();
  let errorTitle;
  c.renderStatus = title => { errorTitle = title; };
  requests[5].resolve({ok: false, status: 503});
  await new Promise(r => global.setImmediate(r));
  assert.equal(errorTitle, 'Could not load tags');
  console.log('PASS: cleared selections and disconnected controllers reject late responses; HTTP failures show an error');
})();
