# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "trix"
pin "@rails/actiontext", to: "actiontext.js"
pin "prismjs", to: "https://ga.jspm.io/npm:prismjs@1.29.0/prism.js"
pin "prismjs/components/prism-ruby", to: "https://ga.jspm.io/npm:prismjs@1.29.0/components/prism-ruby.min.js"
pin "prismjs/components/prism-javascript", to: "https://ga.jspm.io/npm:prismjs@1.29.0/components/prism-javascript.min.js"
pin "prismjs/components/prism-css", to: "https://ga.jspm.io/npm:prismjs@1.29.0/components/prism-css.min.js"
pin "prismjs/components/prism-bash", to: "https://ga.jspm.io/npm:prismjs@1.29.0/components/prism-bash.min.js"
pin "prismjs/components/prism-markup", to: "https://ga.jspm.io/npm:prismjs@1.29.0/components/prism-markup.min.js"
