puts "pending_revisions=#{PostRevision.pending_review.count}"
puts "drafts_revision=#{PostRevision.draft.count}"
puts "drafts_posts=#{Post.where(status: Post.statuses[:draft]).count}"
puts "draft_count_combined=#{PostRevision.draft.count + Post.where(status: Post.statuses[:draft]).count}"
puts "reviewed_today=#{PostRevision.where(moderation_status: [ PostRevision.moderation_statuses[:approved], PostRevision.moderation_statuses[:rejected] ]).where(reviewed_at: Time.current.beginning_of_day..).count}"
puts "new_posts=#{Post.where(status: Post.statuses[:published], verified: false).count}"
